### ISSUE TITLE
The license

### ISSUE THREAD

**Issue by sskras** [henriquencmt/portzcan#1]
If this is an open source project, assigning a license to it would make some things more clear.

And if you are going to choose a permissive license here, I suggest considering the [Blue Oak model license](https://sts10.github.io/2023/01/26/exploring-new-software-licenses.html#the-blue-oak-model-license-a-permissive-license-published-in-2019). It's written by an I.P. Lawyer who writes code and who [was dissatisfied with the existing](https://blueoakcouncil.org/2019/03/06/model.html) permissive licenses.

This issue is just to share the information that looks useful and nice :)

**Comment by henriquencmt** [comment]
I intend to assign a license here soon and will definitely consider this one.

Thanks a lot for sharing!
